version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    restart: unless-stopped
    depends_on:
      - cadvisor
      - node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - ./config/nodeexporter:/etc/nodeexporter/
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
      - "--collector.textfile.directory=/etc/nodeexporter"
    restart: unless-stopped
    ports:
      - 9100:9100

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.6
    container_name: cadvisor
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  prometheus-aas-router:
    container_name: router
    build:
      context: ./build/router
      dockerfile: Dockerfile
    depends_on:
      - prometheus
      - node-exporter
      - cadvisor
    volumes:
      - ./config/prometheus-aas-router:/app/config
      - ./config/aas-server:/usr/share/config
    restart: unless-stopped
    environment:
      - PROMETHEUS_HOST=prometheus
      - PROMETHEUS_PORT=9090
      - AAS_SERVER_HOST=localhost
      - AAS_SERVER_PORT=4001
      - REGISTRY_URL=http://${REGISTRY_HOST_FQDN}:4000/registry
      - SERVER_URL=http://localhost:4001/aasServer
      - HOSTPATH_URL=http://${HOSTNAME_FQDN}:4001/aasServer/shells  
      - UPDATER_CONFIG_DIR=./config
      - AASX_PATH=/usr/share/config/minimalAAS.aasx
      - ASSET_ID=${ASSET_ID}
    ports:
      - 4001:4001

  # registry:
  #   container_name: registry
  #   image: eclipsebasyx/aas-registry:1.0.4
  #   ports:
  #     - 4000:4000
    # networks:
    #   monitor-net:
    #     aliases:
          # - "registry"

volumes:
  prometheus-data:
    driver: local
