global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  # - "rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]
    # file_sd_configs:
    #   - files:
    #       - "targets/*.yml"
